### Global parameter
@baseUrl = http://localhost:3000
@accessToken = Bearer {{Login.response.body.data.accessToken}}
@refreshToken = {{Login.response.body.data.refreshToken}}
@accessTokenReNew = {{RefreshToken.response.body.data.accessToken}}
@refreshTokenReNew = {{RefreshToken.response.body.data.refreshToken}}

#################################################################

@authRoute = authentication

###
# @name Login
POST {{baseUrl}}/{{authRoute}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "administrator",
    "password": "admin@123456"
}

###
# @name RefreshToken
POST {{baseUrl}}/{{authRoute}}/refresh-token HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###
# @name Logout
POST {{baseUrl}}/{{authRoute}}/logout HTTP/1.1
Authorization: {{accessToken}}
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###################################################################
@userRoute = users

###
# @name GetUserList
GET {{baseUrl}}/{{userRoute}} HTTP/1.1
Authorization: {{accessToken}}

###
# @name GetUserById
GET {{baseUrl}}/{{userRoute}}/1 HTTP/1.1
Authorization: {{accessToken}}

###
# @name AddUser
POST {{baseUrl}}/{{userRoute}} HTTP/1.1
Authorization: {{accessToken}}
Content-Type: application/json

{
    "username": "Client1",
    "password": "client@123456",
    "fullName": "client",
    "phone": "09087654321",
    "email": "client@client.com",
    "address": "TpHCM",
    "statusId": "1",
    "createdBy": "0",
    "updatedBy": "0"
}

###
# @name EditUser
PUT {{baseUrl}}/{{userRoute}}/4 HTTP/1.
Authorization: {{accessToken}}
Content-Type: application/json

{
    "username": "client5",
    "password": "client@123456",
    "fullName": "client",
    "phone": "09087654321",
    "email": "client@client.com",
    "address": "TpHCM123",
    "statusId": "1",
    "createdBy": "0",
    "updatedBy": "0"
}

###
# @name DeleteUser
DELETE {{baseUrl}}/{{userRoute}}/2 HTTP/1.1
Authorization: {{accessToken}}

###################################################################
@rolesRoute = roles

###
# @name GetRoleList
GET {{baseUrl}}/{{rolesRoute}} HTTP/1.1
Authorization: {{accessToken}}

###
# @name GetRoleById
GET {{baseUrl}}/{{rolesRoute}}/2 HTTP/1.1
Authorization: {{accessToken}}

###
# @name AddRole
POST {{baseUrl}}/{{rolesRoute}} HTTP/1.1
Authorization: {{accessToken}}
Content-Type: application/json

{

}

###
# @name EditRole
PUT {{baseUrl}}/{{rolesRoute}} HTTP/1.1
Authorization: {{accessToken}}
Content-Type: application/json

{

}

###
# @name DeleteRole
DELETE {{baseUrl}}/{{rolesRoute}}/1 HTTP/1.1
Authorization: {{accessToken}}

###################################################################
@permissionRoute = permissions

###
# @name GetPermissionList
GET {{baseUrl}}/{{permissionRoute}} HTTP/1.1
Authorization: {{accessToken}}

###
# @name GetPermissionById
GET {{baseUrl}}/{{permissionRoute}}/2 HTTP/1.1
Authorization: {{accessToken}}

###
# @name AddPermission
POST {{baseUrl}}/{{permissionRoute}} HTTP/1.1
Authorization: {{accessToken}}
Content-Type: application/json

{

}

###
# @name EditPermission
PUT {{baseUrl}}/{{permissionRoute}} HTTP/1.1
Authorization: {{accessToken}}
Content-Type: application/json

{

}

###
# @name DeletePermission
DELETE {{baseUrl}}/{{permissionRoute}}/1 HTTP/1.1
Authorization: {{accessToken}}