### Global parameter
@baseUrl = http://localhost:3000
@accessToken = Bearer {{Login.response.body.data.accessToken}}
@refreshToken = {{Login.response.body.data.refreshToken}}
@accessTokenReNew = {{RefreshToken.response.body.data.accessToken}}
@refreshTokenReNew = {{RefreshToken.response.body.data.refreshToken}}

#################################################################

@authRoute = authentications

###
# @name Login
POST {{baseUrl}}/{{authRoute}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "administrator",
    "password": "admin@123456"
}

###
# @name RefreshToken
POST {{baseUrl}}/{{authRoute}}/refresh-token HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###
# @name Logout
POST {{baseUrl}}/{{authRoute}}/logout HTTP/1.1
Authorization: {{accessToken}}
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###################################################################
@userRoute = users

###
# @name GetUserList
GET {{baseUrl}}/{{userRoute}} HTTP/1.1
Authorization: {{accessToken}}

###
# @name GetUserById
GET {{baseUrl}}/{{userRoute}}/1 HTTP/1.1
Authorization: {{accessToken}}

###
# @name AddUser
POST {{baseUrl}}/{{userRoute}} HTTP/1.1
Authorization: {{accessToken}}
Content-Type: application/json

{
    "username": "Client1",
    "password": "client@123456",
    "fullName": "client",
    "phone": "09087654321",
    "email": "client@client.com",
    "address": "TpHCM",
    "statusId": "1",
    "createdBy": "0",
    "updatedBy": "0"
}

###
# @name EditUser
PUT {{baseUrl}}/{{userRoute}}/4 HTTP/1.
Authorization: {{accessToken}}
Content-Type: application/json

{
    "username": "client5",
    "password": "client@123456",
    "fullName": "client",
    "phone": "09087654321",
    "email": "client@client.com",
    "address": "TpHCM123",
    "statusId": "1",
    "createdBy": "0",
    "updatedBy": "0"
}

###
# @name DeleteUser
DELETE {{baseUrl}}/{{userRoute}}/2 HTTP/1.1
Authorization: {{accessToken}}

###
# @name Test
GET {{baseUrl}} HTTP/1.1

###
POST {{baseUrl}}/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="images"

--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="README.md"

< ./README.md
--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="DATABASE.md"

< ./DATABASE.md
--WebAppBoundary--
